services:
  db:
    image: mysql:8.0
    container_name: seosan-mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: seosan_issue_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$DB_PASSWORD"]
      interval: 5s
      timeout: 20s
      retries: 10
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  crawler:
    build:
      context: ./crawler
      dockerfile: Dockerfile
    container_name: seosan-crawler-api
    ports:
      - "5001:5001"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    env_file:
      - ./.env
    environment:
      PORT: 5001
      DB_HOST: db
      DB_NAME: seosan_issue_db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: seosan-backend-app
    ports:
      - "8083:8083"
    depends_on:
      db:
        condition: service_healthy
      crawler:
        condition: service_started
    restart: always
    env_file:
      - ./.env
    environment:
      PORT: 8083
      CRAWLER_API_URL: http://crawler:5001
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/seosan_issue_db?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_PROFILES_ACTIVE: prod

volumes:
  db-data:
