services:
  # MySQL 데이터베이스
  - type: private_service
    name: db
    env: docker
    dockerImage: mysql:8.0
    plan: free
    envVars:
      - key: MYSQL_DATABASE
        value: seosan_issue_db
      - key: MYSQL_ROOT_PASSWORD
        sync: false
      - key: TZ
        value: Asia/Seoul
    volumes:
      - name: db-data
        mountPath: /var/lib/mysql

  # Python 크롤러 API
  - type: web
    name: crawler
    env: docker
    dockerfilePath: crawler/Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: "5001"
      - key: DB_HOST
        value: db
      - key: DB_NAME
        value: seosan_issue_db
      - key: DB_PASSWORD
        sync: false
      - key: NAVER_CLIENT_ID
        sync: false
      - key: NAVER_CLIENT_SECRET
        sync: false
      - key: KMA_SERVICE_KEY
        sync: false

  # Spring Boot 백엔드
  - type: web
    name: backend
    env: docker
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: SERVER_PORT
        value: "8083"
      - key: DB_HOST
        value: db
      - key: DB_NAME
        value: seosan_issue_db
      - key: DB_PASSWORD
        sync: false
      - key: CRAWLER_API_URL
        value: http://crawler:5001
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://db:3306/seosan_issue_db?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: NAVER_CLIENT_ID
        sync: false
      - key: NAVER_CLIENT_SECRET
        sync: false
      - key: KMA_SERVICE_KEY
        sync: false

volumes:
  - name: db-data
