# This workflow builds and pushes Docker images to Docker Hub when code is pushed to the main branch.

name: Build and Push Docker Images

# 1. 트리거 설정: main 브랜치에 push 이벤트가 발생했을 때 실행
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest # 실행 환경: 최신 우분투

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Docker Hub 로그인 (GitHub Secrets 사용)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Docker Buildx 설정 (멀티-플랫폼 빌드를 위한 설정)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. 백엔드 이미지 빌드 및 푸시
      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/seosan-issue-backend:latest

      # 5. 크롤러 이미지 빌드 및 푸시
      - name: Build and push Crawler image
        uses: docker/build-push-action@v5
        with:
          context: ./crawler
          file: ./crawler/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/seosan-issue-crawler:latest
